<?xml version="1.0" ?>
<!DOCTYPE schema_er [ <!ELEMENT schema_er (le_entita, le_relazioni, le_generalizzazioni, note)> <!ELEMENT documentazione (#PCDATA)><!ELEMENT vincoli (#PCDATA)><!ELEMENT altro (#PCDATA)><!ELEMENT le_entita (entita)*><!ELEMENT le_relazioni (relazione)*><!ELEMENT le_generalizzazioni (generalizzazione)*>  <!ELEMENT note (documentazione, vincoli, altro) > <!ELEMENT entita (nome, attributo+,idesterna,note)><!ATTLIST entita id ID #REQUIRED> <!ELEMENT nome (#PCDATA)><!ELEMENT idesterna (#PCDATA)> <!ELEMENT attributo (#PCDATA)><!ATTLIST attributo chiave ID #REQUIRED> <!ELEMENT Rel (nome, associazioni+, note)><!ELEMENT associazioni (associazione)*> <!ELEMENT associazione (entitacoll,molteplicita)> <!ELEMENT entitacoll (#PCDATA)><!ATTLIST entitacoll href IDREF #REQUIRED> <!ELEMENT molteplicita (#PCDATA)> <!ELEMENT generalizzazione (padre, figlio+, completa, note)><!ELEMENT padre (#PCDATA)><!ATTLIST padre href IDREF #REQUIRED> <!ELEMENT figlio (#PCDATA)><!ATTLIST figlio href IDREF #REQUIRED> <!ELEMENT completa (#PCDATA)> ]>
<schema_er>
	<le_entita>
		<entita id="1">
			<nome>Utente</nome>
			<attributo chiave="false">Email</attributo>
			<attributo chiave="false">Nome</attributo>
			<attributo chiave="false">Cognome</attributo>
			<attributo chiave="false">Password</attributo>
			<attributo chiave="true">CodiceFiscale</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="2">
			<nome>Menu</nome>
			<attributo chiave="true">Id</attributo>
			<attributo chiave="false">Nome</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="4">
			<nome>Piatto</nome>
			<attributo chiave="true">Id</attributo>
			<attributo chiave="false">Nome</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="6">
			<nome>Alimento</nome>
			<attributo chiave="false">Nome</attributo>
			<attributo chiave="true">Id</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="7">
			<nome>Ingrediente</nome>
			<attributo chiave="false">Nome</attributo>
			<attributo chiave="false">Calorie</attributo>
			<attributo chiave="true">Id</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="10">
			<nome>UtenteAUSL</nome>
			<attributo chiave="false">Password</attributo>
			<attributo chiave="true">Email</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="12">
			<nome>RichiestaModifica</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="14">
			<nome>RichiestaModifica</nome>
			<attributo chiave="false">Data</attributo>
			<attributo chiave="false">Approvato</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="17">
			<nome>UtenteCucina</nome>
			<attributo chiave="true">Username</attributo>
			<attributo chiave="false">Password</attributo>
			<attributo chiave="false">Email</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
	</le_entita>
	<le_relazioni>
		<relazione>
			<nome></nome>
			<associazioni>
				<associazione>
					<entitacoll href="1">Utente</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="2">Menu</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ComposizioneMenu</nome>
			<associazioni>
				<associazione>
					<entitacoll href="2">Menu</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="4">Piatto</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ComposizioneAlimento</nome>
			<associazioni>
				<associazione>
					<entitacoll href="7">Ingrediente</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="6">Alimento</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ComposizionePiatto</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">Alimento</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="4">Piatto</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>Creazione</nome>
			<associazioni>
				<associazione>
					<entitacoll href="10">UtenteAUSL</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="2">Menu</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome></nome>
			<associazioni>
				<associazione>
					<entitacoll href="14">RichiestaModifica</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="2">Menu</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome></nome>
			<associazioni>
				<associazione>
					<entitacoll href="1">Utente</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="14">RichiestaModifica</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome></nome>
			<associazioni>
				<associazione>
					<entitacoll href="14">RichiestaModifica</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="10">UtenteAUSL</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>AssociazioneCucine</nome>
			<associazioni>
				<associazione>
					<entitacoll href="1">Utente</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="17">UtenteCucina</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
	</le_relazioni>
	<le_generalizzazioni>
	</le_generalizzazioni>
	<note>
		<documentazione></documentazione>
		<vincoli></vincoli>
		<altro></altro>
	</note>
</schema_er>